<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KHLC01201" failures="1" tests="1" name="sample_test" time="11.41" errors="0" timestamp="2025-07-29T17:40:20 JST">
  <testcase classname="scenario.InoueScenarioTest" name="scenarioTest001" time="7.188">
    <failure type="java.lang.AssertionError" message="expected [test.jpd.co.jp] but found [test@jpd.co.jp]">
      <![CDATA[java.lang.AssertionError: expected [test.jpd.co.jp] but found [test@jpd.co.jp]
at scenario.TestBase.assertText(TestBase.java:73)
at scenario.InoueScenarioTest.scenarioTest001(InoueScenarioTest.java:84)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- scenarioTest001 -->
</testsuite> <!-- sample_test -->
